### ISSUE TITLE
Update has broken auto-complete

### ISSUE THREAD

**Issue by jamesboswell** [robbyrussell/oh-my-zsh#5179]
Just ran update, and started getting `compdef` errors.  I've disabled all plugins but `z`,  and still auto complete with `z` is broken,  but the compdef errors stopped

```
[Oh My Zsh] Would you like to check for updates? [Y/n]: y
Updating Oh My Zsh
remote: Counting objects: 33, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 33 (delta 21), reused 22 (delta 10), pack-reused 0
Unpacking objects: 100% (33/33), done.
From https://github.com/robbyrussell/oh-my-zsh
 * branch            master     -> FETCH_HEAD
   137a554..d012402  master     -> origin/master
 plugins/emacs/emacsclient.sh                         | 29 ++++++++++++++++++++++-------
 plugins/osx/README.md                                | 27 +++++++++++++++++++++++++++
 plugins/osx/_man-preview                             |  5 -----
 plugins/osx/osx.plugin.zsh                           | 16 +---------------
 plugins/taskwarrior/_task                            |  9 +++++----
 plugins/zsh-navigation-tools/.config/znt/n-kill.conf |  2 +-
 plugins/zsh-navigation-tools/.config/znt/n-list.conf |  2 +-
 plugins/zsh-navigation-tools/n-help                  | 43 +++++++++++++++++++++++++++++++++++++++++--
 plugins/zsh-navigation-tools/n-history               | 10 +++++-----
 plugins/zsh-navigation-tools/n-list                  |  5 ++++-
 templates/zshrc.zsh-template                         |  2 +-
 tools/install.sh                                     |  6 ------
 12 files changed, 108 insertions(+), 48 deletions(-)
 create mode 100644 plugins/osx/README.md
 delete mode 100644 plugins/osx/_man-preview
First, rewinding head to replay your work on top of it...
Fast-forwarded master to d012402dada1ec7d8796f2f4b04744d817137b4d.
         __                                     __
  ____  / /_     ____ ___  __  __   ____  _____/ /_
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
                        /____/
Hooray! Oh My Zsh has been updated and/or is at the current version.
To keep up on the latest news and updates, follow us on twitter: https://twitter.com/ohmyzsh
Get your Oh My Zsh swag at:  http://shop.planetargon.com/
compdef: unknown command or service: grep
compdef: unknown command or service: grep
compdef: unknown command or service: man
```

```
#plugins=(z git gitfast brew osx pep8 python virtualenv virtualenvwrapper)
plugins=(z)
```

`source .zshrc`  still no `z` love for auto completion,  but `compdef` errors stopped

**Comment by mcornella** [comment]
Try `rm ~/.zcompdump*` and restart your terminal.

**Comment by jamesboswell** [comment]
@mcornella   `rm ~/.zcompdump*` ran,  closed and opened new terminal.   Renabled plugins,  still `compdef` errors.   `z` history seems to work.  Tab auto-completion is broken

**Comment by mcornella** [comment]
Try disabling and reenabling only the osx plugin, I have a hunch it might be that one.

**Comment by mcornella** [comment]
I've pushed a fix for this. Try updating: https://github.com/robbyrussell/oh-my-zsh/commit/9a61336d33a8a6258c0fb838bfa3c9c488e7d898

**Comment by jamesboswell** [comment]
Man compdef fixed.   Still complains about grep
```
Last login: Mon Jun 20 16:22:42 on ttys027
compdef: unknown command or service: grep
compdef: unknown command or service: grep
```

It appears to be `git` and `gitfast` plugins.  If remove them, no `compdef` errors
`plugins=(z git gitfast)`

Still missing tab auto-completion?

**Comment by mcornella** [comment]
Nothing else changed in your update that had a grep command. Let's see if I can track this down...
Please run `zsh -ixc exit &>~/debug-zsh.log` and post the file as a private gist.

**Comment by jamesboswell** [comment]
@mcornella  thank you for looking into it.  I'm really missing the tab completion 
https://gist.github.com/jamesboswell/0b4f2cd0c02fcf2e3d2d2f8b05997e47

**Comment by mcornella** [comment]
Relevant lines:

- L2253-L2275:
```
+/Users/jboswell/.oh-my-zsh/plugins/gitfast/../git/git.plugin.zsh:91> compdef 'gfg=grep'
+compdef:1> local opt autol type func delete eval new i ret=0 cmd svc
+compdef:2> local -a match mbegin mend
+compdef:4> emulate -L zsh
+compdef:5> setopt extendedglob
+compdef:9> ((  ! 1  ))
+compdef:14> getopts anpPkKde opt
+compdef:38> shift OPTIND-1
+compdef:40> ((  ! 1  ))
+compdef:45> [[ -z '' ]]
+compdef:49> [[ -z '' ]]
+compdef:49> [[ 'gfg=grep' == *=* ]]
+compdef:50> ((  1  ))
+compdef:51> [[ 'gfg=grep' == *=* ]]
+compdef:52> cmd=gfg 
+compdef:53> svc=grep 
+compdef:54> func='' 
+compdef:55> [[ -n '' ]]
+compdef:57> [[ -z '' ]]
+compdef:58> func='' 
+compdef:59> [[ -n '' ]]
+compdef:63> print -u2 'compdef: unknown command or service: grep'
compdef: unknown command or service: grep
```

- L1610-L1632:
```
+/Users/jboswell/.oh-my-zsh/plugins/git/git.plugin.zsh:91> compdef 'gfg=grep'
+compdef:1> local opt autol type func delete eval new i ret=0 cmd svc
+compdef:2> local -a match mbegin mend
+compdef:4> emulate -L zsh
+compdef:5> setopt extendedglob
+compdef:9> ((  ! 1  ))
+compdef:14> getopts anpPkKde opt
+compdef:38> shift OPTIND-1
+compdef:40> ((  ! 1  ))
+compdef:45> [[ -z '' ]]
+compdef:49> [[ -z '' ]]
+compdef:49> [[ 'gfg=grep' == *=* ]]
+compdef:50> ((  1  ))
+compdef:51> [[ 'gfg=grep' == *=* ]]
+compdef:52> cmd=gfg 
+compdef:53> svc=grep 
+compdef:54> func='' 
+compdef:55> [[ -n '' ]]
+compdef:57> [[ -z '' ]]
+compdef:58> func='' 
+compdef:59> [[ -n '' ]]
+compdef:63> print -u2 'compdef: unknown command or service: grep'
compdef: unknown command or service: grep
```

This comes from [line 91 of the git plugin](https://github.com/robbyrussell/oh-my-zsh/blob/9a61336/plugins/git/git.plugin.zsh#L91). Apparently, in your zsh installation that doesn't work. Here's the output of `compdef gfg=grep` in my system:
```
+zsh:4> compdef 'gfg=grep'
+compdef:1> local opt autol type func delete eval new i ret=0 cmd svc
+compdef:2> local -a match mbegin mend
+compdef:4> emulate -L zsh
+compdef:5> setopt extendedglob
+compdef:9> ((  ! 1  ))
+compdef:14> getopts anpPkKde opt
+compdef:38> shift OPTIND-1
+compdef:40> ((  ! 1  ))
+compdef:45> [[ -z '' ]]
+compdef:49> [[ -z '' ]]
+compdef:49> [[ 'gfg=grep' == *=* ]]
+compdef:50> ((  1  ))
+compdef:51> [[ 'gfg=grep' == *=* ]]
+compdef:52> cmd=gfg 
+compdef:53> svc=grep 
+compdef:54> func=_grep 
+compdef:55> [[ -n '' ]]
+compdef:57> [[ -z _grep ]]
+compdef:59> [[ -n _grep ]]
+compdef:60> _comps[$cmd]=_grep 
+compdef:61> _services[$cmd]=grep 
+compdef:70> shift
+compdef:50> ((  0  ))
+compdef:73> return ret
```

Presumably fixing that in the same way we fixed the former man-preview completion should be enough. Please try running `compef _grep gfg`; I'm going to go and change that in the meantime.

**Comment by mcornella** [comment]
The weird thing is that this error should have been there for a long time, [the commit](https://github.com/robbyrussell/oh-my-zsh/blame/9a61336/plugins/git/git.plugin.zsh#L91) was part of #2790 which was merged on Jun 11, 2015.

Fixed in https://github.com/robbyrussell/oh-my-zsh/commit/c62442f999854038e7d0911f60a4aff252913a7f, please update.

**Comment by jamesboswell** [comment]
@mcornella ```╰─$ zsh --version                                                                                                                                                                                                         127 ↵
zsh 5.2 (x86_64-apple-darwin14.5.0)```  FYI

**Comment by mcornella** [comment]
Has the update fixed your problem?

**Comment by jamesboswell** [comment]
No longer getting the `compdef` errors,  but  tab completions/suggestions is still missing?

`ls  /` + TAB  used to give suggested completions?

**Comment by jamesboswell** [comment]
@mcornella,  Ok so this is interesting.  

```
╭─jboswell@kratos  ~
╰─$  rm -f ~/.zcompdump*
╭─jboswell@kratos  ~
╰─$ compinit
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? y
╭─jboswell@kratos  ~
╰─$
╭─jboswell@kratos  ~
╰─$
╭─jboswell@kratos  ~
╰─$ ls .z   (TAB key)
.z            .zcompdump    .zsh-update   .zsh_history  .zshrc
```

However, if I open a new terminal session...it's broken again?   Delete `.zcompdump` and `compinit` in new session...and voila TAB works again.

This is 100% reproducible for me so far.

**Comment by mcornella** [comment]
Please run `compaudit` and post the output.

**Comment by mcornella** [comment]
When did this started happening though?

**Comment by jamesboswell** [comment]
```
╰─$ compaudit                                                                                                                                                                                                               
There are insecure directories:
/usr/local/share/zsh/site-functions
/usr/local/Cellar/zsh/5.2/share/zsh/functions
/usr/local/share/zsh
/usr/local/Cellar/zsh/5.2/share/zsh
╰─$ ls -la /usr/local/share/zsh                                                                                                                                                                                             1 ↵
total 0
drwxrwxr-x    6 jboswell  admin    204 Apr  5 13:36 .
drwxrwxr-x   18 root      admin    612 Jun 21 11:00 ..
drwxrwxr-x  982 jboswell  admin  33388 Apr  5 11:17 functions
drwxrwxr-x  110 jboswell  admin   3740 Apr  5 11:17 help
drwxrwxr-x    3 jboswell  admin    102 Apr  5 11:17 scripts
drwxrwxr-x    5 jboswell  admin    170 May 25 02:14 site-functions
```

When I first noticed it was after the most recent auto-update in my first comment above.   These are all symlinks setup by Homebrew.   Could some Homebrew file permissions issue be at fault here?

**Comment by jamesboswell** [comment]
@mcornella  and anyone else experiencing this issue.  This is definitely permissions issues related to Homebrew and OS X El Capitan.    What I can't explain is why it just now manifested for me with recent oh-my-zsh update.   

**Background**:   OS X El Capitan changed some file system permissions as [seen here](https://github.com/Homebrew/legacy-homebrew/issues/41665) that breaks `brew update`    Following directions in the GitHub issue thread,  I changed my permissions for `/usr/local`  with  `sudo chmod -R g+w /usr/local`,   which was probably the _wrong_ thing to do!

**Verifying permissions issue:**
Run `compaudit`   if it looks like this,  you likely have incorrect permissions.   Running it through `stat` will give you the octal permissions
```
$ compaudit                                                                                                                                                                                                               
There are insecure directories:
/usr/local/share/zsh/site-functions
/usr/local/Cellar/zsh/5.2/share/zsh/functions
/usr/local/share/zsh
/usr/local/Cellar/zsh/5.2/share/zsh
$
$compaudit | xargs stat -f %Mp%Lp
There are insecure directories:
0775
0775
0775
0775
 ```
Per[ this thread ](http://stackoverflow.com/questions/13762280/zsh-compinit-insecure-directories)on stackoverflow,  the permisions need to be `0755`.   Also based on[ ZSH mailing list](http://www.zsh.org/mla/users/2008/msg00566.html)

**FIX:**
Chmod the _insecure_ directories to `0755`.   You can do this by passing the following xargs
```
$ compaudit | xargs chmod 755                                                                                                                                                                                             
There are insecure directories:
$
$ # a second compaudit run shows no errors 
$ compaudit
$  
```
Next,  delete your `.zcompdump` files, and run `compinit`
```
$ rm -f ~/.zcompdump*
$ compinit
```

This fixed all auto completion issues for me.   Therefore I am closing this issue.

**Comment by mcornella** [comment]
Thanks for the explanation!

**Comment by zzswang** [comment]
@jamesboswell Thanks a lot.

I've suffered this error for a whole day!
